### ISSUE TITLE
B450 Tomahawk max not supported (Need help)

### ISSUE THREAD

**Issue by JulianTheMen** [ixjf/MSIRGB#133]
When I open the program it says that my motherboard is not supported altough it says in the README it is supported. I would like to know if the b450 tomahawk max is supported or not.

**Comment by ixjf** [comment]
Can you run this command on a command prompt and show me the result?

`wmic path Win32_BaseBoard get Manufacturer, Version, Product`

**Comment by JulianTheMen** [comment]
> Can you run this command on a command prompt and show me the result?
> 
> `wmic path Win32_BaseBoard get Manufacturer, Version, Product`

I will try that tomorrow

**Comment by JulianTheMen** [comment]
![Motherboard](https://user-images.githubusercontent.com/69213018/89394496-6e665100-d70c-11ea-9ef0-4a20a635dc6b.PNG)

Here you go

**Comment by ixjf** [comment]
When you start MSIRGB, it'll prompt you whether to continue or not despite not recognizing it as a supported motherboard. Your motherboard is _reported_ to work, I.e. other users have tried it and told me it works fine. The reason the program doesn't tell you everything is okay is because it is not a motherboard that *I* guaranteed MSIRGB would be compatible with. I'll have to update MSIRGB at some point to include more motherboards.

In short, you should be fine.

**Comment by JulianTheMen** [comment]
Thank you!
