### ISSUE TITLE
Turn off lights at startup script

### ISSUE THREAD

**Issue by afsilvasantos** [ixjf/MSIRGB#151]
Hi,

Is there any function that allows to disable all lights at startup?

**Comment by ixjf** [comment]
You can call `Lighting.SetAllEnabled` with first parameter = `false`. If a script was left running when Windows shutdown, it'll auto-start with Windows as well, so this would have the desired effect.

**Comment by afsilvasantos** [comment]
Ok thanks! That worked out. However i run the script, but when i restart the lights are on again. shouldn't the script run automatically now?

**Comment by ixjf** [comment]
If you ran the script and didn't stop it at any point, it should have. I see two options:

- You have some other program turning them on.
- This is another case of bug #43.

**Comment by ronangelo** [comment]
I have a B450M MB and wanted to disable the lights at startup too. I managed to get it working with this:

```
Lighting.SetAllEnabled(true)

os.sleep( 500 )

Lighting.SetAllEnabled( false )
```

I'm not sure which fixed my issue though. Either setting the `Lighting.SetAllEnabled` to True before disabling OR messing with the service's startup type. I initially set it to Automatic (Delayed Start) but changed it back to Automatic. It's working so far since then.

**Comment by ixjf** [comment]
I updated the scripts to fix this issue. You can see the last comment in #159 (the one with the code example) to see how to apply it to your own code.
