### ISSUE TITLE
is there any tutorial for making own scripts?

### ISSUE THREAD

**Issue by guythatplaysminecraft** [ixjf/MSIRGB#162]
also slider for the brightness control would be nice

**Comment by ixjf** [comment]
There is a wiki (see "Wiki" tab on the main page) documenting the Lua API. There are also example scripts already in the repository. I don't think there is a need for much more since it's all pretty basic. What are you struggling with?

As for brightness control, this isn't supported by any of the motherboards.

**Comment by ixjf** [comment]
I'm closing this issue as the question has been answered. If you need any further help, please comment (unless it's a different problem, in which case, open a new issue or start a discussion - see 'Discussions' tab).
