### ISSUE TITLE
B450-A PRO MAX working

### ISSUE THREAD

**Issue by Shihrt** [ixjf/MSIRGB#89]
Motherboard not bricked, colors working fine.

![cpuz_2020-03-21_18-31-03](https://user-images.githubusercontent.com/15351111/77237864-336ee100-6ba2-11ea-80ac-c151a24300db.jpg)

**Comment by oncle-anatole** [comment]
Are you sure it works correctly because I've the same exact motherboard with the same bios but the behaviour seems a bit random. Unless I've not understood how the software works. It seems when clicking on buttons, the software doesn't register half of the time. Also, the colors are wrong. For instance I put blue on all the squares and the effect I've is pulsing between white (default) and purple. Whatever combination of colors I try to enter, it never shows red. Enabling breathing makes my strips pulse from off to white, no color. etc. Mystic Light isn't installed by the way but I guess I unfortunately will need to because this software doesn't seem to work like intended, it's just too erratic. The scripts seem to work though

**Comment by ixjf** [comment]
> Are you sure it works correctly because I've the same exact motherboard with the same bios but the behaviour seems a bit random. Unless I've not understood how the software works. It seems when clicking on buttons, the software doesn't register half of the time. Also, the colors are wrong. For instance I put blue on all the squares and the effect I've is pulsing between white (default) and purple. Whatever combination of colors I try to enter, it never shows red. Enabling breathing makes my strips pulse from off to white, no color. etc. Mystic Light isn't installed by the way but I guess I unfortunately will need to because this software doesn't seem to work like intended, it's just too erratic. The scripts seem to work though

Guaranteed you have some program interfering with your LEDs. That's the standard behaviour.

**Comment by ixjf** [comment]
> Motherboard not bricked, colors working fine.
> 
> ![cpuz_2020-03-21_18-31-03](https://user-images.githubusercontent.com/15351111/77237864-336ee100-6ba2-11ea-80ac-c151a24300db.jpg)

Thanks!
